[package]
edition      = "2021"
name         = "flowstick"
rust-version = "1.86"
version      = "0.1.0"

[[bin]]
name = "flowstick"
path = "./src/bin/main.rs"

[dependencies]
esp-bootloader-esp-idf = { version = "0.2.0", features = ["esp32s3"] }
esp-hal                = { version = "=1.0.0-rc.0", features = ["esp32s3", "unstable"] }

bleps = { git = "https://github.com/bjoernQ/bleps", package = "bleps", rev = "a5148d8ae679e021b78f53fd33afb8bb35d0b62e", features = [
  "async",
  "macros",
] }
critical-section = "1.2.0"
embedded-io = "0.6.1"
esp-alloc = "0.8.0"
esp-wifi = { version = "0.15.0", features = [
  "ble",
  "builtin-scheduler",
  "esp-alloc",
  "esp32s3",
] }
esp-backtrace = { version = "0.16.0", features = [
    "esp32s3",
    "exception-handler",
    "panic-handler",
    "println",
    "semihosting",  # Not technically correct but prevents USB serial/JTAG from being shut down on panic
]}
esp-println = { version = "0.14.0", features = ["esp32s3", "log-04"] }
log = "0.4.27"
embassy-executor = "0.7.0"
embassy-time = "0.4.0"
esp-hal-embassy = { version = "0.9.0", features = ["esp32s3", "log-04"] }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
