M48
; DRILL file {KiCad 9.0.1} date 2025-07-17T15:45:23-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-17T15:45:23-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.700
%
G90
G05
T1
X147.11Y-94.695
X152.89Y-94.695
T2
X150.0Y-97.0
X150.0Y-98.8
M30
